name: dev_community
description: Dev Flutter app. Enjoy!

publish_to: "none"

version: 0.2.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  very_good_analysis: ^3.1.0
  flutter_riverpod: ^2.0.2
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  go_router: ^5.1.1
  dio: ^4.0.6
  cached_network_image: ^3.2.2

  jiffy: ^5.0.0
  intl: ^0.17.0

  infinite_scroll_pagination: ^3.2.0
  very_good_infinite_list: ^0.6.0+1

  scrolls_to_top: ^2.0.0
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.6

  flutter_widget_from_html: ^0.8.5
  flutter_markdown: ^0.6.12

  flutter_highlight: ^0.7.0

  flutter_svg: ^1.1.5
  expandable_text: ^2.3.0
  share_plus: ^6.2.0
  pull_down_button: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3

  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
