name: data_store
description: Domain specific data store interface
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  drift: ^2.3.0
  path: ^1.8.2
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.2.1

  drift_dev: ^2.2.0+1
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.1.0
